# Generated by Django 5.2.1 on 2025-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='id',
        ),
        migrations.AddField(
            model_name='track',
            name='album_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
