# Generated by Django 5.2.1 on 2025-05-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='free', max_length=10),
        ),
    ]
