# Generated by Django 5.2.1 on 2025-05-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_user_username_alter_user_image_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
